"""
Load Balancer Package Builder

Automatically generates load balancer configurations and deployment packages
for Fleet Server clusters. Supports multiple deployment options:
- Docker Compose (HAProxy)
- Native Linux (HAProxy/Nginx)
- macOS with Docker
"""
import json
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Dict, Any, List, Optional
import logging

logger = logging.getLogger(__name__)


class LoadBalancerBuilder:
    """Build load balancer configurations and deployment packages"""
    
    def __init__(self):
        """Initialize load balancer builder"""
        self.temp_dir = None
    
    def build_package(self, output_path: str, lb_config: Dict[str, Any]) -> tuple[bool, str]:
        """
        Build load balancer deployment package
        
        Args:
            output_path: Where to save the package
            lb_config: Load balancer configuration including node IPs
        
        Returns:
            (success, message/error)
        """
        try:
            # Create temporary build directory
            self.temp_dir = Path(tempfile.mkdtemp(prefix='lb_pkg_'))
            logger.info(f"Building load balancer package in: {self.temp_dir}")

            # Get configuration
            nodes = lb_config.get('nodes', [])
            lb_port = lb_config.get('port', 8778)
            lb_name = lb_config.get('name', 'fleet-lb')

            if not nodes:
                return False, "No cluster nodes specified"

            # Create package structure
            pkg_dir = self.temp_dir / 'fleet-loadbalancer'
            pkg_dir.mkdir(parents=True, exist_ok=True)

            # Generate HAProxy configuration
            haproxy_config = self._generate_haproxy_config(nodes, lb_port)
            (pkg_dir / 'haproxy.cfg').write_text(haproxy_config)

            # Generate Nginx configuration
            nginx_config = self._generate_nginx_config(nodes, lb_port)
            (pkg_dir / 'nginx.conf').write_text(nginx_config)

            # Generate Docker Compose file (easiest deployment)
            docker_compose = self._generate_docker_compose(nodes, lb_port, lb_name)
            (pkg_dir / 'docker-compose.yml').write_text(docker_compose)

            # Generate installation script for Linux
            linux_install = self._generate_linux_install_script(nodes, lb_port)
            linux_script_path = pkg_dir / 'install-haproxy-linux.sh'
            linux_script_path.write_text(linux_install)
            linux_script_path.chmod(0o755)

            # Generate macOS Docker setup script
            macos_install = self._generate_macos_docker_script(nodes, lb_port)
            macos_script_path = pkg_dir / 'install-docker-macos.sh'
            macos_script_path.write_text(macos_install)
            macos_script_path.chmod(0o755)

            # Generate README
            readme = self._generate_readme(nodes, lb_port)
            (pkg_dir / 'README.md').write_text(readme)

            # Generate node list for reference
            nodes_json = {
                'nodes': nodes,
                'port': lb_port,
                'name': lb_name,
                'health_check_url': '/api/fleet/cluster/health'
            }
            with open(pkg_dir / 'cluster-nodes.json', 'w') as f:
                json.dump(nodes_json, f, indent=2)
            
            # Create tarball
            import tarfile
            with tarfile.open(output_path, 'w:gz') as tar:
                tar.add(pkg_dir, arcname='fleet-loadbalancer')
            
            logger.info(f"Successfully built load balancer package: {output_path}")
            return True, f"Package created successfully: {output_path}"
        
        except Exception as e:
            logger.error(f"Error building load balancer package: {e}", exc_info=True)
            return False, f"Error: {str(e)}"

        finally:
            # Cleanup temp directory
            if self.temp_dir and self.temp_dir.exists():
                try:
                    shutil.rmtree(self.temp_dir)
                except Exception as e:
                    logger.warning(f"Failed to cleanup temp dir: {e}")
    
    def _generate_haproxy_config(self, nodes: List[Dict], port: int) -> str:
        """Generate HAProxy configuration"""
        
        # Build server list
        servers = []
        for i, node in enumerate(nodes, 1):
            node_id = node.get('id', f'node{i}')
            node_host = node.get('host', f'10.0.1.{100+i}')
            node_port = node.get('port', 8778)
            servers.append(f"    server {node_id} {node_host}:{node_port} check inter 3s fall 2 rise 2")
        
        servers_config = '\n'.join(servers)
        
        return f'''# HAProxy Configuration for Fleet Server Cluster
# Auto-generated by Fleet Server Load Balancer Builder

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    
    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    
    # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  forwardfor
    option  http-server-close
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# Fleet Server Frontend
# This is what admins/users access
frontend fleet_frontend
    bind *:{port}
    mode http
    default_backend fleet_servers
    
    # Optional: Force HTTPS redirect
    # redirect scheme https code 301 if !{{ ssl_fc }}

# Fleet Server Backend
# Your cluster nodes
backend fleet_servers
    mode http
    balance roundrobin
    
    # Health check configuration
    option httpchk GET /api/fleet/cluster/health
    http-check expect status 200
    
    # Cluster nodes (auto-generated)
{servers_config}

# Stats page (optional)
# Access at http://<lb-ip>:9000/stats
listen stats
    bind *:9000
    mode http
    stats enable
    stats uri /stats
    stats refresh 5s
    stats realm HAProxy\\ Statistics
    stats auth admin:changeme
    # Change password above!
'''
    
    def _generate_nginx_config(self, nodes: List[Dict], port: int) -> str:
        """Generate Nginx configuration"""
        
        # Build upstream servers
        servers = []
        for i, node in enumerate(nodes, 1):
            node_host = node.get('host', f'10.0.1.{100+i}')
            node_port = node.get('port', 8778)
            servers.append(f"        server {node_host}:{node_port} max_fails=2 fail_timeout=5s;")
        
        servers_config = '\n'.join(servers)
        
        return f'''# Nginx Configuration for Fleet Server Cluster
# Auto-generated by Fleet Server Load Balancer Builder

events {{
    worker_connections 1024;
}}

http {{
    # Upstream cluster nodes
    upstream fleet_cluster {{
{servers_config}
        
        # Health checks (requires nginx-plus or external module)
        # For open source nginx, use passive health checks above
    }}
    
    # Load balancer server
    server {{
        listen {port};
        server_name _;
        
        # Logging
        access_log /var/log/nginx/fleet-access.log;
        error_log /var/log/nginx/fleet-error.log;
        
        # Proxy to cluster
        location / {{
            proxy_pass http://fleet_cluster;
            proxy_http_version 1.1;
            
            # Headers
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Timeouts
            proxy_connect_timeout 5s;
            proxy_send_timeout 50s;
            proxy_read_timeout 50s;
            
            # Buffering
            proxy_buffering off;
            proxy_cache_bypass $http_upgrade;
        }}
        
        # Health check endpoint (for external monitoring)
        location /lb-health {{
            access_log off;
            return 200 "healthy\\n";
            add_header Content-Type text/plain;
        }}
    }}
    
    # Optional: Status page
    # Uncomment to enable at http://<lb-ip>:9000/nginx_status
    # server {{
    #     listen 9000;
    #     location /nginx_status {{
    #         stub_status on;
    #         access_log off;
    #     }}
    # }}
}}
'''
    
    def _generate_docker_compose(self, nodes: List[Dict], port: int, name: str) -> str:
        """Generate Docker Compose file for HAProxy"""
        
        # Build server list for HAProxy config
        servers = []
        for i, node in enumerate(nodes, 1):
            node_id = node.get('id', f'node{i}')
            node_host = node.get('host', f'10.0.1.{100+i}')
            node_port = node.get('port', 8778)
            servers.append(f"    server {node_id} {node_host}:{node_port} check inter 3s fall 2 rise 2")
        
        return f'''version: '3.8'

services:
  haproxy:
    image: haproxy:2.8-alpine
    container_name: {name}
    restart: unless-stopped
    ports:
      - "{port}:{port}"
      - "9000:9000"  # Stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - fleet-network
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  fleet-network:
    driver: bridge

# Usage:
# 1. Ensure haproxy.cfg is in the same directory
# 2. Run: docker-compose up -d
# 3. Check stats: http://localhost:9000/stats (admin/changeme)
# 4. Access Fleet: http://localhost:{port}
'''
    
    def _generate_linux_install_script(self, nodes: List[Dict], port: int) -> str:
        """Generate installation script for Linux"""
        
        return f'''#!/bin/bash
# HAProxy Installation Script for Fleet Server Load Balancer
# Auto-generated - Run on Ubuntu/Debian Linux

set -e

echo "=========================================="
echo "Fleet Server Load Balancer Installation"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo "Cannot detect operating system"
    exit 1
fi

echo "Detected OS: $OS"
echo ""

# Install HAProxy
echo "Installing HAProxy..."
if [ "$OS" = "ubuntu" ] || [ "$OS" = "debian" ]; then
    apt-get update
    apt-get install -y haproxy
elif [ "$OS" = "centos" ] || [ "$OS" = "rhel" ] || [ "$OS" = "fedora" ]; then
    yum install -y haproxy
else
    echo "Unsupported OS: $OS"
    exit 1
fi

# Backup existing config
if [ -f /etc/haproxy/haproxy.cfg ]; then
    echo "Backing up existing HAProxy config..."
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup.$(date +%s)
fi

# Copy new configuration
echo " Installing Fleet Server HAProxy configuration..."
cp haproxy.cfg /etc/haproxy/haproxy.cfg

# Validate configuration
echo "✓ Validating HAProxy configuration..."
haproxy -c -f /etc/haproxy/haproxy.cfg

# Enable and start HAProxy
echo "Starting HAProxy..."
systemctl enable haproxy
systemctl restart haproxy

# Wait a moment
sleep 2

# Check status
if systemctl is-active --quiet haproxy; then
    echo ""
    echo "HAProxy installed and running successfully!"
    echo ""
    echo "Access Points:"
    echo "   Fleet Server: http://$(hostname -I | awk '{{print $1}}'):{port}"
    echo "   Stats Page:   http://$(hostname -I | awk '{{print $1}}'):9000/stats"
    echo "                 (Username: admin, Password: changeme)"
    echo ""
    echo "Management Commands:"
    echo "   Status:  sudo systemctl status haproxy"
    echo "   Stop:    sudo systemctl stop haproxy"
    echo "   Start:   sudo systemctl start haproxy"
    echo "   Restart: sudo systemctl restart haproxy"
    echo "   Logs:    sudo journalctl -u haproxy -f"
    echo ""
    echo " IMPORTANT: Change the stats password in /etc/haproxy/haproxy.cfg"
    echo ""
else
    echo ""
    echo "HAProxy failed to start"
    echo "Check logs with: sudo journalctl -u haproxy -n 50"
    exit 1
fi

exit 0
'''
    
    def _generate_macos_docker_script(self, nodes: List[Dict], port: int) -> str:
        """Generate Docker installation script for macOS"""
        
        return f'''#!/bin/bash
# Docker-based HAProxy Installation for macOS
# Auto-generated - Run on macOS with Docker Desktop installed

set -e

echo "=========================================="
echo "Fleet Server Load Balancer (Docker)"
echo "=========================================="
echo ""

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Docker is not installed"
    echo ""
    echo "Please install Docker Desktop from:"
    echo "https://www.docker.com/products/docker-desktop"
    echo ""
    exit 1
fi

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo "Docker is not running"
    echo ""
    echo "Please start Docker Desktop and try again"
    echo ""
    exit 1
fi

echo "Docker is installed and running"
echo ""

# Check if docker-compose is available
if ! command -v docker-compose &> /dev/null; then
    echo " docker-compose not found, using 'docker compose' instead"
    COMPOSE_CMD="docker compose"
else
    COMPOSE_CMD="docker-compose"
fi

# Stop any existing container
echo "🛑 Stopping any existing load balancer..."
$COMPOSE_CMD down 2>/dev/null || true

# Start HAProxy
echo "Starting HAProxy load balancer..."
$COMPOSE_CMD up -d

# Wait for container to be healthy
echo "⏳ Waiting for load balancer to be ready..."
sleep 3

# Check if running
if docker ps | grep -q fleet-lb; then
    echo ""
    echo "Load balancer is running!"
    echo ""
    echo "Access Points:"
    echo "   Fleet Server: http://localhost:{port}"
    echo "   Stats Page:   http://localhost:9000/stats"
    echo "                 (Username: admin, Password: changeme)"
    echo ""
    echo "Management Commands:"
    echo "   Status:  docker ps | grep fleet-lb"
    echo "   Logs:    docker logs -f fleet-lb"
    echo "   Stop:    $COMPOSE_CMD down"
    echo "   Restart: $COMPOSE_CMD restart"
    echo ""
    echo "To make load balancer start on boot:"
    echo "   1. Open Docker Desktop"
    echo "   2. Settings → General"
    echo "   3. Enable 'Start Docker Desktop when you log in'"
    echo ""
else
    echo ""
    echo "Failed to start load balancer"
    echo "Check logs with: docker logs fleet-lb"
    exit 1
fi

exit 0
'''
    
    def _generate_readme(self, nodes: List[Dict], port: int) -> str:
        """Generate comprehensive README"""
        
        nodes_list = '\n'.join([f"- {node.get('id', f'node{i+1}')}: {node.get('host', 'unknown')}:{node.get('port', 8778)}" 
                                for i, node in enumerate(nodes)])
        
        return f'''# Fleet Server Load Balancer Package

**Auto-generated load balancer configuration for your Fleet Server cluster**

## Cluster Configuration

Your cluster has **{len(nodes)} node(s)**:

{nodes_list}

**Load Balancer Port:** {port}

---

## Quick Start

### Option 1: Docker (Recommended for macOS)

**Prerequisites:**
- Docker Desktop installed and running

**Steps:**
```bash
# Make script executable
chmod +x install-docker-macos.sh

# Run installation
./install-docker-macos.sh

# Access Fleet Server
open http://localhost:{port}
```

**Done! Your load balancer is running in Docker.**

---

### Option 2: Linux Server (Ubuntu/Debian)

**Prerequisites:**
- Ubuntu/Debian Linux server
- Root/sudo access

**Steps:**
```bash
# Make script executable
chmod +x install-haproxy-linux.sh

# Run installation
sudo ./install-haproxy-linux.sh

# Access Fleet Server
# http://<your-server-ip>:{port}
```

**Done! HAProxy is installed and running as a system service.**

---

### Option 3: Manual Docker Compose

**Steps:**
```bash
# Start load balancer
docker-compose up -d

# Check status
docker-compose ps

# View logs
docker-compose logs -f

# Stop load balancer
docker-compose down
```

---

## What's Included

This package contains:

- **`haproxy.cfg`** - HAProxy configuration file
- **`nginx.conf`** - Nginx configuration (alternative to HAProxy)
- **`docker-compose.yml`** - Docker Compose setup
- **`install-haproxy-linux.sh`** - Automated Linux installation
- **`install-docker-macos.sh`** - Automated macOS/Docker installation
- **`cluster-nodes.json`** - Node configuration reference
- **`README.md`** - This file

---

## Access Points

After installation:

| Service | URL | Credentials |
|---------|-----|-------------|
| **Fleet Server** | `http://<lb-ip>:{port}` | Your Fleet admin account |
| **HAProxy Stats** | `http://<lb-ip>:9000/stats` | admin / changeme |

**IMPORTANT:** Change the stats password after installation!

---

## 🏥 Health Checks

The load balancer automatically monitors node health:

- **Health Check URL:** `/api/fleet/cluster/health`
- **Check Interval:** 3 seconds
- **Failure Threshold:** 2 consecutive failures
- **Recovery Threshold:** 2 consecutive successes

When a node fails health checks, traffic is automatically routed to healthy nodes.

---

## Verification

### Check Load Balancer Status:

**Docker:**
```bash
docker ps | grep fleet-lb
docker logs fleet-lb
```

**Linux:**
```bash
sudo systemctl status haproxy
sudo journalctl -u haproxy -f
```

### Test Load Balancing:

```bash
# Check cluster status
curl http://localhost:{port}/api/fleet/cluster/status

# Should show all your nodes
```

### View Stats:

Open `http://localhost:9000/stats` in browser:
- Username: `admin`
- Password: `changeme` (change this!)

---

## Configuration

### Adding/Removing Nodes

**Docker/HAProxy:**
1. Edit `haproxy.cfg`
2. Add/remove server lines in the `backend fleet_servers` section:
   ```
   server node4 10.0.1.103:8778 check inter 3s fall 2 rise 2
   ```
3. Restart: `docker-compose restart` or `sudo systemctl restart haproxy`

**Nginx:**
1. Edit `nginx.conf`
2. Add/remove server lines in the `upstream fleet_cluster` section
3. Restart: `sudo systemctl restart nginx`

### Changing Port

1. Edit configuration file (`haproxy.cfg` or `nginx.conf`)
2. Change `bind *:{port}` to your desired port
3. Restart load balancer

---

## 🐛 Troubleshooting

### Docker Won't Start

```bash
# Check Docker is running
docker info

# Check container logs
docker logs fleet-lb

# Restart Docker Desktop (macOS)
```

### HAProxy Won't Start (Linux)

```bash
# Check configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# View logs
sudo journalctl -u haproxy -n 50

# Check if port is in use
sudo netstat -tlnp | grep :{port}
```

### Nodes Showing as Down

```bash
# Check node is running
curl http://<node-ip>:{port}/api/fleet/cluster/health

# Check firewall
# Ensure load balancer can reach nodes on port {port}

# Check HAProxy stats page
# http://<lb-ip>:9000/stats
```

### Can't Access Stats Page

Default credentials:
- Username: `admin`
- Password: `changeme`

Change password in configuration file:
```
stats auth admin:your-new-password
```

---

## Security Best Practices

### 1. Change Stats Password

Edit configuration file:
```
stats auth admin:your-secure-password
```

### 2. Enable HTTPS

Add SSL certificate to HAProxy:
```
frontend fleet_frontend
    bind *:443 ssl crt /path/to/certificate.pem
```

### 3. Restrict Stats Access

Add IP whitelist:
```
listen stats
    bind *:9000
    acl allowed_ips src 10.0.1.0/24
    http-request deny if !allowed_ips
```

### 4. Firewall Rules

Only allow necessary ports:
- {port} - Fleet Server
- 9000 - Stats page (restrict to admin IPs)

---

## 📚 Additional Resources

### HAProxy Documentation
- https://www.haproxy.org/
- https://docs.haproxy.org/

### Nginx Documentation
- https://nginx.org/en/docs/
- https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/

### Docker Documentation
- https://docs.docker.com/

---

## Summary

Your Fleet Server load balancer is configured with:

- **{len(nodes)} cluster nodes**
- **Port {port}** for Fleet Server access
- **Port 9000** for stats/monitoring
- **Automatic health checks** every 3 seconds
- **Automatic failover** on node failure

**Access your Fleet Server at:**
```
http://<load-balancer-ip>:{port}
```

Share this URL with all admins and users!

---

**Questions or issues? Check Fleet Server documentation or logs.**
'''


def build_loadbalancer_package(output_path: str, nodes: List[Dict[str, Any]], 
                               port: int = 8778, name: str = 'fleet-lb') -> tuple[bool, str]:
    """
    Build load balancer deployment package
    
    Args:
        output_path: Where to save the .tar.gz package
        nodes: List of cluster nodes with 'id', 'host', 'port'
        port: Load balancer port (default 8778)
        name: Container/service name
    
    Returns:
        (success, message)
    """
    lb_config = {
        'nodes': nodes,
        'port': port,
        'name': name
    }
    
    builder = LoadBalancerBuilder()
    return builder.build_package(output_path, lb_config)
